---
on:
  push:
    branches:
      - main
      - staging
      - develop
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: semantic-release
        uses: ahmadnassri/action-semantic-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
